{
    'name': 'Appscomp Fleet Management',
    'version': '15.0.1',
    'category': 'Managing vehicles and contracts',
    "license": "LGPL-3",
    'summary': 'Appscomp Fleet Management',
    'description': """ Appscomp Fleet Management """,
    'author': 'appscomp',
    'website': 'www.appscomp.com',
    'depends': ['approvals','gate_entry','fleet'],
    'images': [''],
    'data': [
        'security/ir.model.access.csv',
        'data/mail_template_data.xml',
        'views/employee_fleet_view.xml',
        'views/fleet_approvals.xml',
        'views/fleet_approval_category.xml',
        'views/driver_beta.xml',
        'views/driver_history.xml',
        'views/driver_ot_sheet_view.xml',
        'views/vehicle_pass_view.xml',
        'views/approval_request_for_fleet_view.xml',
        'views/two_wheeler_vehicle_view.xml',
        'views/multiple_approval_single_vehicle.xml',
        'wizard/driver_trip_details.xml',
        'wizard/driver_ot_sheet_view_wizard.xml',
        'wizard/four_wheeler_usage_report_view.xml',
        'wizard/one_way_trip_wizard.xml',
        'report/fleet_usage_report_pdf.xml',
    ],
    'installable': True,
    'application': False,
}

