from odoo import models, fields, api, _
import xlwt
from io import BytesIO
import base64
import itertools
from operator import itemgetter
from odoo.exceptions import Warning
from odoo import tools
from xlwt import easyxf
import datetime
from odoo.exceptions import UserError
from datetime import datetime
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from odoo.exceptions import Warning, ValidationError, UserError
import pdb

cell = easyxf('pattern: pattern solid, fore_colour yellow')
ADDONS_PATH = tools.config['addons_path'].split(",")[-1]

MONTH_LIST = [('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'),
              ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'),
              ('7', 'Jul'), ('8', 'Aug'), ('9', 'Sep'),
              ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')]


class PurchaseOrderSummaryExcelReport(models.TransientModel):
    _name = 'purchase.order.excel.report.wizard'
    _description = ' Purchase Order Summary Excel Report'

    start_date = fields.Date('Start date')
    end_date = fields.Date('End date')
    attachment = fields.Binary('File')
    attach_name = fields.Char('Attachment Name')
    summary_file = fields.Binary('Purchase Order Summary Report')
    file_name = fields.Char('File Name')
    report_printed = fields.Boolean('Purchase Summary Report')
    current_time = fields.Date('Current Time', default=lambda self: fields.Datetime.now())
    ams_time = datetime.now() + timedelta(hours=5, minutes=30)
    date = ams_time.strftime('%d-%m-%Y %H:%M:%S')
    user_id = fields.Many2one('res.users', 'User', default=lambda self: self.env.user)


    def action_get_purchase_order_excel_report(self):
        workbook = xlwt.Workbook()
        worksheet1 = workbook.add_sheet('PURCAHSE SUMMARY REPORT')
        design_6 = easyxf('align: horiz left;font: bold 1;')
        design_7 = easyxf('align: horiz center;font: bold 1;')
        design_8 = easyxf('align: horiz left;')
        design_9 = easyxf('align: horiz right;')
        design_10 = easyxf('align: horiz right; pattern: pattern solid, fore_colour red;')
        design_11 = easyxf('align: horiz right; pattern: pattern solid, fore_colour green;')
        design_12 = easyxf('align: horiz right; pattern: pattern solid, fore_colour gray25;')
        design_13 = easyxf('align: horiz center;font: bold 1;pattern: pattern solid, fore_colour gray25;')
        design_14 = easyxf('align: horiz left;font: bold 1;pattern: pattern solid, fore_colour gray25;')
        design_15 = easyxf('align: horiz right;font: bold 1;pattern: pattern solid, fore_colour gray25;')
        design_16 = easyxf('align: horiz center;font: bold 1;pattern: pattern solid, fore_colour gray25;')
        design_17 = easyxf("pattern: pattern solid, fore_color black; font: color white; align: horiz center")
        design_18 = easyxf('align: horiz right; font: bold 1;')

        worksheet1.col(0).width = 2000
        worksheet1.col(1).width = 3500
        worksheet1.col(2).width = 7000
        worksheet1.col(3).width = 8000
        worksheet1.col(4).width = 6000
        worksheet1.col(5).width = 2800
        worksheet1.col(6).width = 2800
        worksheet1.col(7).width = 3000
        worksheet1.col(8).width = 5000
        worksheet1.col(9).width = 6000


        rows = 0
        cols = 0
        row_pq = 5
        col_pq = 5

        worksheet1.set_panes_frozen(True)
        worksheet1.set_horz_split_pos(rows + 1)



        col_1 = 0
        worksheet1.write_merge(rows, rows, 2, 3, 'PURCHASE SUMMARY  REPORT', design_16)
        rows += 1
        worksheet1.write(rows, 2, 'START DATE', design_14)
        worksheet1.write(rows, 3, self.start_date.strftime('%d-%m-%Y'), design_13)
        rows += 1
        worksheet1.write(rows, 2, 'END DATE', design_14)
        worksheet1.write(rows, 3, self.end_date.strftime('%d-%m-%Y'), design_13)
        rows += 1
        worksheet1.write(rows, 2, 'REPORT GENERATED BY', design_14)
        worksheet1.write(rows, 3, self.user_id.name, design_13)
        rows += 2
        worksheet1.write(rows, col_1, _('S.NO'), design_13)
        col_1 += 1
        worksheet1.write(rows, col_1, _('PO DATE'), design_13)
        col_1 += 1
        worksheet1.write(rows, col_1, _('PO No'), design_13)
        col_1 += 1
        worksheet1.write(rows, col_1, _('Product Category'), design_13)
        col_1 += 1
        worksheet1.write(rows, col_1, _(' Product Description'), design_13)
        col_1 += 1
        worksheet1.write(rows, col_1, _('QTY'), design_13)
        col_1 += 1
        worksheet1.write(rows, col_1, _('UOM'), design_13)
        col_1 += 1
        worksheet1.write(rows, col_1, _('RATE'), design_13)
        col_1 += 1
        worksheet1.write(rows, col_1, _('TOTAL AMOUNT'), design_13)
        col_1 += 1
        worksheet1.write(rows, col_1, _('Status'), design_13)
        col_1 += 1
        sl_no = 1
        row_pq = row_pq + 1
        mr_num = []
        res = []
        total = 0
        for record in self:
            domain = [
                ('date_order', '>=', record.start_date),
                ('date_order', '<=', record.end_date),
                ('state', 'not in', ('draft', 'reject', 'cancel'))
            ]
            if record.start_date and record.end_date:
                purchase_summary = record.env['purchase.order'].sudo().search(domain, order='date_order asc')
                for po in purchase_summary.order_line:
                    worksheet1.write(row_pq, 0, sl_no, design_7)
                    if po.order_id.date_order:
                        worksheet1.write(row_pq, 1, po.order_id.date_order.strftime('%d-%m-%Y'), design_8)
                    else:
                        worksheet1.write(row_pq, 1, '-', design_7)
                    if po.order_id.name:
                        worksheet1.write(row_pq, 2, po.order_id.name, design_8)
                    else:
                        worksheet1.write(row_pq, 2, '-', design_7)
                    if po.product_template_id.categ_id:
                        worksheet1.write(row_pq, 3, po.product_template_id.categ_id.name, design_8)
                    else:
                        worksheet1.write(row_pq, 3, '-', design_7)
                    if po.name:
                        worksheet1.write(row_pq, 4, po.name, design_8)
                    else:
                        worksheet1.write(row_pq, 4, '-', design_7)
                    if po.product_qty:
                        worksheet1.write(row_pq, 5, po.product_qty, design_9)
                    else:
                        worksheet1.write(row_pq, 5, '-', design_9)
                    if po.product_template_id.uom_po_id:
                        worksheet1.write(row_pq, 6, po.product_template_id.uom_po_id.name, design_8)
                    else:
                        worksheet1.write(row_pq, 6, '-', design_7)
                    if po.price_unit:
                        worksheet1.write(row_pq, 7, po.price_unit, design_9)
                    else:
                        worksheet1.write(row_pq, 7, '-', design_9)
                    if po.price_subtotal:
                        total += po.price_subtotal
                        worksheet1.write(row_pq, 8,
                                         po.order_id.company_id.currency_id.symbol + str('%.2f' % po.price_subtotal)
                                         , design_9)
                    else:
                        worksheet1.write(row_pq, 8, '-', design_9)
                    if po.order_id.state:
                        state = ''
                        if po.order_id.state == 'sent':
                            state = 'Sent RFQ'
                        elif po.order_id.state == 'to_approve':
                            state = 'To Approve'
                        elif po.order_id.state == 'to_be_approved':
                            state = 'Waiting 1st Level Approval'
                        elif po.order_id.state == 'leader_approval':
                            state = 'Waiting 2nd Level Approval'
                        elif po.order_id.state == 'manager_approval':
                            state = 'Waiting 3rd Level Approval'
                        elif po.order_id.state == 'director_approval':
                            state = 'Waiting 4th Level Approval'
                        elif po.order_id.state == 'ceo_approval':
                            state = 'Waiting 5th Level Approval'
                        elif po.order_id.state == 'final_approval':
                            state = 'Waiting Final Approval'
                        elif po.order_id.state == 'request_approved':
                            state = 'Approved'
                        elif po.order_id.state == 'purchase':
                            state = 'Purchase Order'
                        elif po.order_id.state == 'done':
                            state = 'Done'
                        elif po.order_id.state == 'request_to_approve':
                            state = 'Request to Approve'
                        po_summary_state = state
                        worksheet1.write(row_pq, 9, po_summary_state, design_8)
                    else:
                        worksheet1.write(row_pq, 9, '-', design_7)

                    sl_no += 1
                    row_pq += 1
                worksheet1.write(row_pq, 7, 'Total Value', design_7)
                worksheet1.write(row_pq, 8, po.order_id.company_id.currency_id.symbol + str('%.2f' %total), design_18)
        fp = BytesIO()
        o = workbook.save(fp)
        fp.read()
        excel_file = base64.b64encode(fp.getvalue())
        self.write({'summary_file': excel_file, 'file_name': 'Purchase Order Summary Report -[ %s ] [ %s ].xls' % (
            self.start_date.strftime('%d-%m-%Y'), record.end_date.strftime('%d-%m-%Y')),
                    'report_printed': True})
        fp.close()
        return {
            'view_mode': 'form',
            'res_id': self.id,
            'res_model': 'purchase.order.excel.report.wizard',
            'view_type': 'form',
            'type': 'ir.actions.act_window',
            'context': self.env.context,
            'target': 'new',
        }
